/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.invento.temporizador;

import java.awt.event.ActionEvent;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import javax.swing.Timer;

/**
 *
 * @author Branny Gonzales
 */
public class JFrmTemporizador extends javax.swing.JFrame {

    private static JFrmTemporizador INSTANCIA = null;
    private Timer timer;
    
    /**
     * Creates new form JFrmTemporizador
     */
    private JFrmTemporizador() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    public static JFrmTemporizador getInstance() {
        if (INSTANCIA == null) {
            INSTANCIA = new JFrmTemporizador();
        }
        return INSTANCIA;
    }

    public void asignarMinutoInicial(int minutoInicial) {
        if (timer != null) {
            timer.stop();
        }
        
        Temporizador temporizador = Temporizador.getInstance();
        temporizador.establecerTemporizador(minutoInicial, 0);
        timer = new Timer(1000, (ActionEvent e) -> {
            System.out.println("Tiempo: " + LocalDateTime.ofInstant(Instant.ofEpochMilli(System.currentTimeMillis()), 
                    ZoneId.systemDefault()));
            jlblTiempo.setText(temporizador.obtenerTemporizador());
            temporizador.establecerTemporizador(temporizador.obtenerSiguienteMinuto(), 
                    temporizador.obtenerSiguienteSegundo());
        });
        timer.start();
    }
    
    public void detenerTemporizador() {
        if (timer != null) {
            timer.stop();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblTiempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temporizador");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlblTiempo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTiempo.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblTiempo, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (timer != null) {
            timer.stop();
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblTiempo;
    // End of variables declaration//GEN-END:variables
}
